### PR TITLE
Granular control options

### PR DESCRIPTION
**Pull request by cfreear**
Adds ``doPanning``, ``doPinchZoom`` and ``doWheelZoom`` to control plugin behaviour.
Moves default options into an extended object to allow for boolean defaults.
Adds option breakdown and example to readme.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
there is something wrong with the diff. Which branch did you fork?

**Comment by cfreear** [comment]
master, was that wrong?

Edit: just taken a look at the diff, does it look wrong because of the additional entries in ``/dist/svg.panzoom.js``?

**Comment by Fuzzyma** [comment]
No not at all. We just might need to merge #13 first and you need to rebase then :)

**Comment by cfreear** [comment]
ah I see, fair enough!

**Comment by Fuzzyma** [comment]
@cfreear can you please resolve the merge conflict? We changed quite a lot :)

**Comment by cfreear** [comment]
Done, let me know if you want any changes making

**Comment by Bernix01** [comment]
any update on this?

**Comment by Fuzzyma** [comment]
I totally forgot about this and coming back after like 3 years. Sorry to everyone. I will merge it myself asap

**Pull request merged**
