### PR TITLE
Min and max level of zoom

### PR DESCRIPTION
**Pull request by inanisvitae**
By passing zoomMin and zoomMax as parameters to panZoom can elegantly solve the problem that min and max levels cannot be set.

### CODE REVIEW

**Review by dotnetCarpenter — APPROVED** [review]

**Comment by Fuzzyma** [comment]
There is a problem with this PR.
You dont necessarily call `panZoom()` before you call `zoom()` so the min and max values might be not set at this point. `zoom()` can be used as normal function. Its not tied to `panZoom` at all. Thats why it is so tricky to add min and max zoom

**Comment by Fuzzyma** [comment]
@dotnetCarpenter we might need to revert this

**Comment by dotnetCarpenter** [comment]
@Fuzzyma hmm.. so `zoom` is defined on all elements before calling `panZoom()`?

**Comment by dotnetCarpenter** [comment]
Damn.. I just published this.

**Comment by inanisvitae** [comment]
My version works for me lol. It would be troublesome to do it the way you guys described

**Comment by dotnetCarpenter** [comment]
@Fuzzyma We can check for existence of max/min. I'll update and publish a 1.1.1

**Comment by Fuzzyma** [comment]
It remains a hack. We need to think about this :D

**Comment by dotnetCarpenter** [comment]
@Fuzzyma Will you publish to npm? I don't have access

**Comment by Fuzzyma** [comment]
iam confused - didnt you just say that you published this?

**Comment by dotnetCarpenter** [comment]
If we get a lot of optional variables, then yes, I agree it is not beautiful. But for the two, max/min, it seems reasonable.
Perhaps a cleaner approach would be to use `Object.defineProperty` with getter/setter to get/set values across `zoom` and `panZoom`.

I published to github, which is the same as publishing to bower but not npm.

**Comment by Fuzzyma** [comment]
I would leave it unpublished for now and revert it back because of the reasons above. I really dont like hacks like this. I would even prefer `zoom(level, zoo, min, max)` over the current one.
There is no difference in setting it directly or using defineProperty. It remains code smell.

**Comment by Fuzzyma** [comment]
This is even producing another bug. If you call panZoom one time with min and max you not even can zoom over the max value programatically

**Comment by dotnetCarpenter** [comment]
you can set `zoomMax`/`zoomMin` at any time.

```js
var world = SVG('world').panZoom({zoomMax: 3})
...
world.zoomMax = 5
world.zoom(5)
```

**Comment by Fuzzyma** [comment]
Why not just:

```js
var wheelZoom = function(ev) {
  ev.preventDefault()

  if(ev.deltaY == 0) return

  var zoomAmount = this.zoom() - zoomFactor * ev.deltaY/Math.abs(ev.deltaY)
    , p = this.point(ev.clientX, ev.clientY)

  zoomAmount = Math.min(Math.max(zoomAmount, min), max)
    
  this.zoom(zoomAmount, p)
}
```

where min and max are passed as options

**Comment by dotnetCarpenter** [comment]
Or you can have different panzooms - see here https://worldmap.surge.sh/
The left buttons has a max/min while the right buttons does not.

**Comment by Fuzzyma** [comment]
Well thats exactly the programatically zoom iam talking about. Please take a look at my answer above. I cant test it atm. I am working on the 3.0 branch and plugins do not work atm

**Pull request merged**
