### PR TITLE
Docs + cleanup WheelZoomDeltaMode*

### PR DESCRIPTION
**Pull request by jonenst**

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Thank you!

**Comment by jonenst** [comment]
You're welcome! Do you have an idea on when you are going to release this ?

**Comment by jonenst** [comment]
and thank you for writing this library :)

**Comment by Fuzzyma** [comment]
Because you asked so nicely I did it right away ;).

**Comment by jonenst** [comment]
That's awesome, many thanks for all the quick replies !

**Pull request merged**
