### PR TITLE
wheel zoom by multiplication

### PR DESCRIPTION
**Pull request by lexelby**
When zooming in really far, it starts to take forever to zoom any more.  The further you go in, the less "sensitive" the mouse wheel feels.  

I've fixed this by multiplying by the zoom factor, rather than adding it.  For example, for a zoom factor of 0.03, it will multiply the current zoom by 1.03 for every tick of the mouse wheel.  This appears to naturally magnify by the same amount regardless of the current scale, and it feels much more natural.

I had to fork off of 1.2.3 because my project is using svg.js v2.  I'm not quite sure what's changed and whether I can go to svg.js v3 in an Electron project.  Hopefully you can at least get the idea from my commit.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
can you please rebase your PR on the current master and force push? I cannot see your changes like this

**Comment by lexelby** [comment]
Hi!  I'm not sure when I'll have a chance to rebase, but I think @kaalleen may have already done so in our fork.

**Comment by Fuzzyma** [comment]
We integrated this in the libraray now. We just need to release it. It indeed feels so much more natural. Thank you for pointing out!

**Comment by lexelby** [comment]
Oh hooray, thank you!

**Pull request closed without merging**
